name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Welcome
        run: echo "welcome"

  run_tests:
    runs-on: ubuntu-latest
    needs: [build]
    environment: development
    continue-on-error: true
    steps:
      - name: running tests
        run: |
          echo "running tests"
          exit 1

  manual-approval-on-failure:
    runs-on: ubuntu-latest
    needs: run_tests # This job depends on build-and-test
    # The 'if' condition is key:
    # 1. 'always()' ensures this job runs even if 'build-and-test' failed.
    # 2. 'needs.build-and-test.result == 'failure'' ensures it only runs if 'build-and-test' *did* fail.
    if: ${{ always() && needs.run_tests.result == 'failure' }}
    steps:
      - name: Manual Approval Gate
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }} # Required for the action to interact with GitHub API
          minimum-approvals: 1
          issue-title: "Manual Approval Required: Preceding Job Failed!"
          issue-body: |
            The 'build-and-test' job failed. Please review the logs and approve if you wish to proceed despite this failure.
            Workflow Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          # approval-wait: 600 # Optional: Timeout in seconds for approval (e.g., 10 minutes)


  deploy_development:
    runs-on: ubuntu-latest
    needs: [run_tests]
    if: ${{ needs.run_tests.result == 'success' }}
    environment: development
    steps:
      - name: Deploying production
        run: echo "deploying to development"
