name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Welcome
        run: echo" welcome"

  deploy_development:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Deploying production
        run: echo "deploying to development"

  deploy_production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploying production
        run: echo "deploying to production"
