name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Welcome
        run: echo "welcome"

  run_tests:
    runs-on: ubuntu-latest
    needs: [build]
    environment: development
    continue-on-error: true
    steps:
      - name: running tests
        run: |
          echo "running tests"
          exit 1
 
  deploy_development:
    runs-on: ubuntu-latest
    needs: [run_tests]
    environment: development
    steps:
      - name: Deploying production
        run: echo "deploying to development"

  deploy_production:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [deploy_development]
    environment: production
    steps:
      - name: Deploying production
        run: echo "deploying to production"
