
name: Test scripts

on:
  workflow_call:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    outputs:
        my-var: ${{ steps.run-scripts.outputs.my-variable }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run scripts
        id: run-scripts
        run: |
          chmod +x ./script.sh
          sh ./script.sh
      - name: test output
        run: |
          echo "my variable - ${{ steps.run-scripts.outputs.my-variable}}"
