
name: Test output script

on:
  push:

jobs:
  run-scripts:
    strategy:
      matrix:
        region: ["eu", "apac"]
    uses: ./.github/workflows/reusable.yml

  another-job:
    runs-on: ubuntu-latest
    needs: run-scripts
    steps:
      - name: run scripts
        run: |
          echo "${{ needs.run-scripts.outputs.my-var }}"
          echo "${{ toJSON(needs.run-scripts.outputs.*.my-var) }}"